# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 501)
        MainWindow.setMinimumSize(QtCore.QSize(0, 50))
        MainWindow.setStyleSheet("#centralwidget{\n"
"    \n"
"    \n"
"}\n"
"QFrame{    \n"
"    background-color:#333\n"
"    \n"
"}\n"
"QLabel{\n"
"    font-size:25px;\n"
"    font-family:\"Helvetica\";\n"
"    color: #fff;\n"
"}\n"
"QLineEdit{\n"
"    font-size:30px;\n"
"    font-family:\"Helvetica\";\n"
"    background-color:#333;\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    color:#fff;\n"
"}\n"
"/* all*/\n"
"#centralwidget #frame_2 QPushButton{\n"
"    color:#fff;\n"
"    background-color: #000000;\n"
"    font-size: 25px;\n"
"    font-family: \"Helvetica\";\n"
"    border-radius: 20px;\n"
"}\n"
"#centralwidget #frame_2 QPushButton:pressed{\n"
"    background-color: #555;\n"
"}\n"
"\n"
"/* number*/\n"
"#centralwidget #frame_2 #frame_3 QPushButton{\n"
"    color:#fff;\n"
"    background-color: #000000;\n"
"    font-size: 25px;\n"
"    width:40px;\n"
"    height:40px;\n"
"    border-radius: 20px;\n"
"}\n"
"#centralwidget #frame_2 #frame_3 QPushButton[class=\"operand\"]{\n"
"    color:#000000;\n"
"    background-color: #fff;\n"
"}\n"
"#centralwidget #frame_2 #frame_3 QPushButton:pressed{\n"
"    background-color: #555;\n"
"}\n"
"/* sin cos*/\n"
"#centralwidget #frame_2 #frame_4 QPushButton{\n"
"    color:#000000;\n"
"    background-color: #fff;\n"
"    font-size: 25px;\n"
"    width:40px;\n"
"    height:40px;\n"
"    \n"
"}\n"
"#centralwidget #frame_2 #frame_4 QPushButton:pressed{\n"
"    background-color: #555;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_5)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.outputfield = QtWidgets.QLineEdit(parent=self.frame_5)
        self.outputfield.setMinimumSize(QtCore.QSize(0, 60))
        self.outputfield.setText("")
        self.outputfield.setObjectName("outputfield")
        self.verticalLayout.addWidget(self.outputfield)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 140, 351, 201))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.plus = QtWidgets.QPushButton(parent=self.frame_3)
        self.plus.setMinimumSize(QtCore.QSize(0, 0))
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 0, 0, 1, 1)
        self.minus = QtWidgets.QPushButton(parent=self.frame_3)
        self.minus.setMinimumSize(QtCore.QSize(0, 0))
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 0, 1, 1, 1)
        self.multiple = QtWidgets.QPushButton(parent=self.frame_3)
        self.multiple.setMinimumSize(QtCore.QSize(0, 0))
        self.multiple.setObjectName("multiple")
        self.gridLayout.addWidget(self.multiple, 0, 2, 1, 1)
        self.divide = QtWidgets.QPushButton(parent=self.frame_3)
        self.divide.setMinimumSize(QtCore.QSize(0, 0))
        self.divide.setObjectName("divide")
        self.gridLayout.addWidget(self.divide, 0, 3, 1, 1)
        self.one = QtWidgets.QPushButton(parent=self.frame_3)
        self.one.setMinimumSize(QtCore.QSize(0, 0))
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 1, 0, 1, 1)
        self.two = QtWidgets.QPushButton(parent=self.frame_3)
        self.two.setMinimumSize(QtCore.QSize(0, 0))
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 1, 1, 1, 1)
        self.three = QtWidgets.QPushButton(parent=self.frame_3)
        self.three.setMinimumSize(QtCore.QSize(0, 0))
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 1, 2, 1, 1)
        self.zero = QtWidgets.QPushButton(parent=self.frame_3)
        self.zero.setMinimumSize(QtCore.QSize(0, 0))
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 1, 3, 1, 1)
        self.four = QtWidgets.QPushButton(parent=self.frame_3)
        self.four.setMinimumSize(QtCore.QSize(0, 0))
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 2, 0, 1, 1)
        self.five = QtWidgets.QPushButton(parent=self.frame_3)
        self.five.setMinimumSize(QtCore.QSize(0, 0))
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 2, 1, 1, 1)
        self.six = QtWidgets.QPushButton(parent=self.frame_3)
        self.six.setMinimumSize(QtCore.QSize(0, 0))
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 2, 2, 1, 1)
        self.open = QtWidgets.QPushButton(parent=self.frame_3)
        self.open.setMinimumSize(QtCore.QSize(0, 0))
        self.open.setObjectName("open")
        self.gridLayout.addWidget(self.open, 2, 3, 1, 1)
        self.seven = QtWidgets.QPushButton(parent=self.frame_3)
        self.seven.setMinimumSize(QtCore.QSize(0, 0))
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 3, 0, 1, 1)
        self.eight = QtWidgets.QPushButton(parent=self.frame_3)
        self.eight.setMinimumSize(QtCore.QSize(0, 0))
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 3, 1, 1, 1)
        self.nine = QtWidgets.QPushButton(parent=self.frame_3)
        self.nine.setMinimumSize(QtCore.QSize(0, 0))
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 3, 2, 1, 1)
        self.close = QtWidgets.QPushButton(parent=self.frame_3)
        self.close.setMinimumSize(QtCore.QSize(0, 0))
        self.close.setObjectName("close")
        self.gridLayout.addWidget(self.close, 3, 3, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(380, 180, 251, 161))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.power = QtWidgets.QPushButton(parent=self.frame_4)
        self.power.setMinimumSize(QtCore.QSize(0, 40))
        self.power.setObjectName("power")
        self.gridLayout_2.addWidget(self.power, 0, 0, 1, 1)
        self.abs = QtWidgets.QPushButton(parent=self.frame_4)
        self.abs.setMinimumSize(QtCore.QSize(0, 40))
        self.abs.setObjectName("abs")
        self.gridLayout_2.addWidget(self.abs, 1, 2, 1, 1)
        self.varx = QtWidgets.QPushButton(parent=self.frame_4)
        self.varx.setMinimumSize(QtCore.QSize(0, 0))
        self.varx.setObjectName("varx")
        self.gridLayout_2.addWidget(self.varx, 0, 2, 1, 1)
        self.cos = QtWidgets.QPushButton(parent=self.frame_4)
        self.cos.setMinimumSize(QtCore.QSize(0, 40))
        self.cos.setObjectName("cos")
        self.gridLayout_2.addWidget(self.cos, 1, 1, 1, 1)
        self.sqrt = QtWidgets.QPushButton(parent=self.frame_4)
        self.sqrt.setMinimumSize(QtCore.QSize(0, 40))
        self.sqrt.setObjectName("sqrt")
        self.gridLayout_2.addWidget(self.sqrt, 0, 1, 1, 1)
        self.sin = QtWidgets.QPushButton(parent=self.frame_4)
        self.sin.setMinimumSize(QtCore.QSize(0, 40))
        self.sin.setObjectName("sin")
        self.gridLayout_2.addWidget(self.sin, 1, 0, 1, 1)
        self.resultfield = QtWidgets.QLineEdit(parent=self.frame_2)
        self.resultfield.setGeometry(QtCore.QRect(400, 40, 221, 91))
        self.resultfield.setText("")
        self.resultfield.setObjectName("resultfield")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(480, 10, 81, 20))
        self.label_2.setObjectName("label_2")
        self.info = QtWidgets.QPushButton(parent=self.frame_2)
        self.info.setGeometry(QtCore.QRect(450, 140, 121, 28))
        self.info.setStyleSheet("background-color:#333")
        self.info.setObjectName("info")
        self.frame = QtWidgets.QFrame(parent=self.frame_2)
        self.frame.setGeometry(QtCore.QRect(50, 60, 311, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete_2 = QtWidgets.QPushButton(parent=self.frame)
        self.delete_2.setMinimumSize(QtCore.QSize(0, 40))
        self.delete_2.setStyleSheet("background-color:#fff;\n"
"color:#000000")
        self.delete_2.setObjectName("delete_2")
        self.horizontalLayout.addWidget(self.delete_2)
        self.ac = QtWidgets.QPushButton(parent=self.frame)
        self.ac.setMinimumSize(QtCore.QSize(0, 40))
        self.ac.setStyleSheet("background-color:#cc0000")
        self.ac.setObjectName("ac")
        self.horizontalLayout.addWidget(self.ac)
        self.solve = QtWidgets.QPushButton(parent=self.frame)
        self.solve.setMinimumSize(QtCore.QSize(0, 40))
        self.solve.setStyleSheet("background-color:#ff6600;")
        self.solve.setObjectName("solve")
        self.horizontalLayout.addWidget(self.solve)
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Math Calculator"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.plus.setProperty("class", _translate("MainWindow", "operand"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.minus.setProperty("class", _translate("MainWindow", "operand"))
        self.multiple.setText(_translate("MainWindow", "*"))
        self.multiple.setProperty("class", _translate("MainWindow", "operand"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.divide.setProperty("class", _translate("MainWindow", "operand"))
        self.one.setText(_translate("MainWindow", "1"))
        self.one.setProperty("class", _translate("MainWindow", "num"))
        self.two.setText(_translate("MainWindow", "2"))
        self.two.setProperty("class", _translate("MainWindow", "num"))
        self.three.setText(_translate("MainWindow", "3"))
        self.three.setProperty("class", _translate("MainWindow", "num"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.zero.setProperty("class", _translate("MainWindow", "num"))
        self.four.setText(_translate("MainWindow", "4"))
        self.four.setProperty("class", _translate("MainWindow", "num"))
        self.five.setText(_translate("MainWindow", "5"))
        self.five.setProperty("class", _translate("MainWindow", "num"))
        self.six.setText(_translate("MainWindow", "6"))
        self.six.setProperty("class", _translate("MainWindow", "num"))
        self.open.setText(_translate("MainWindow", "("))
        self.open.setProperty("class", _translate("MainWindow", "num"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.seven.setProperty("class", _translate("MainWindow", "num"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.eight.setProperty("class", _translate("MainWindow", "num"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.nine.setProperty("class", _translate("MainWindow", "num"))
        self.close.setText(_translate("MainWindow", ")"))
        self.close.setProperty("class", _translate("MainWindow", "num"))
        self.power.setText(_translate("MainWindow", "^"))
        self.power.setProperty("class", _translate("MainWindow", "operand"))
        self.abs.setText(_translate("MainWindow", "abs"))
        self.abs.setProperty("class", _translate("MainWindow", "operand"))
        self.varx.setText(_translate("MainWindow", "x"))
        self.varx.setProperty("class", _translate("MainWindow", "operand"))
        self.cos.setText(_translate("MainWindow", "cos"))
        self.cos.setProperty("class", _translate("MainWindow", "operand"))
        self.sqrt.setText(_translate("MainWindow", "sqrt"))
        self.sqrt.setProperty("class", _translate("MainWindow", "operand"))
        self.sin.setText(_translate("MainWindow", "sin"))
        self.sin.setProperty("class", _translate("MainWindow", "operand"))
        self.label_2.setText(_translate("MainWindow", "Result"))
        self.info.setText(_translate("MainWindow", "Xem info"))
        self.delete_2.setText(_translate("MainWindow", "DEL"))
        self.ac.setText(_translate("MainWindow", "AC"))
        self.solve.setText(_translate("MainWindow", "Solve"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
